{
 "title": "Room Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "aranet4_co2_ppm", "legendFormat": " " }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "aranet4_temperature_c", "legendFormat": " " }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "aranet4_humidity_percent", "legendFormat": " " }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "aranet4_pressure_hpa + 24", "legendFormat": " " }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "aranet4_battery_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
   "targets": [
    { "expr": "sum(aranet4_error) by (reason)", "legendFormat": "__auto" }
   ]
  }
 ]
}